package com.discountscreener.android.domain.usecase

data class DashboardUseCases(
    val observeDashboardUpdates: ObserveDashboardUpdatesUseCase,
    val bootstrapDashboard: BootstrapDashboardUseCase,
    val refreshDashboard: RefreshDashboardUseCase,
    val getDashboardSnapshot: GetDashboardSnapshotUseCase,
    val selectDashboardSymbol: SelectDashboardSymbolUseCase,
    val addDashboardSymbols: AddDashboardSymbolsUseCase,
    val selectDashboardProfile: SelectDashboardProfileUseCase,
    val toggleDashboardWatchlist: ToggleDashboardWatchlistUseCase,
    val loadScoringPreferences: LoadScoringPreferencesUseCase,
    val persistScoringPreferences: PersistScoringPreferencesUseCase,
    val loadSystemStats: LoadSystemStatsUseCase,
    val pruneOldRevisions: PruneOldRevisionsUseCase,
    val clearAllData: ClearAllDataUseCase,
    val exportScores: ExportScoresUseCase,
    val runRetrospective: RunRetrospectiveUseCase,
    val getIndexEstimates: GetIndexEstimatesUseCase,
    val saveEstimatesSnapshot: SaveEstimatesSnapshotUseCase,
    val getEstimatesHistory: GetEstimatesHistoryUseCase,
    val searchTickers: SearchTickersUseCase,
    val loadDiscoverySnapshot: LoadDiscoverySnapshotUseCase,
    val saveDiscoveryConfig: SaveDiscoveryConfigUseCase,
    val recreateDiscoveryUniverse: RecreateDiscoveryUniverseUseCase,
    val refreshDiscoveryScores: RefreshDiscoveryScoresUseCase,
    val cancelDiscoveryJob: CancelDiscoveryJobUseCase,
    val clearDiscoveryData: ClearDiscoveryDataUseCase,
    val observeDiscoveryProgress: ObserveDiscoveryProgressUseCase,
)
