// Email composition — polished, inline-styled, email-client-safe HTML.
// Table-based layout, solid colors (no fl/grid/gradient), max-width 600px.

import type { SetupLabel } from "./api";

type Lang = "es" | "en";

// Subject prefix so the user can filter these into an Outlook/Gmail folder.
const SUBJECT_PREFIX = "[Vantage]";

export interface EmailChange {
  symbol: string;
  company: string | null;
  from: SetupLabel;
  to: SetupLabel;
  score: number;
  priceCents: number;
  dailyChangeBps: number | null;
}

export interface EmailOpportunity {
  symbol: string;
  company: string | null;
  label: SetupLabel;
  score: number;
  priceCents: number;
  sector: string | null;
  upsidePct: number | null; // vs analyst target
  dailyChangeBps: number | null;
  earningsEpoch: number | null;
}

export interface EmailRiskAlert {
  symbol: string;
  text: string;
  severity: "warn" | "danger";
}

export interface DigestData {
  changes: EmailChange[];
  opportunities: EmailOpportunity[];
  risks: EmailRiskAlert[];
  lang: Lang;
  now: Date;
}

// ── palette ──
const C = {
  bg: "#0f172a",
  card: "#ffffff",
  ink: "#0f172a",
  sub: "#64748b",
  line: "#e2e8f0",
  zebra: "#f8fafc",
  green: "#16a34a",
  red: "#dc2626",
  amber: "#d97706",
  gray: "#64748b",
  accent: "#2563eb",
};

const POS: SetupLabel[] = ["StrongBuy", "Buy", "Accumulate", "StrongAccumulate"];
const NEG: SetupLabel[] = ["Avoid", "StrongAvoid", "Caution", "Distribute"];

const LABELS: Record<SetupLabel, { es: string; en: string }> = {
  StrongBuy: { es: "Compra fuerte", en: "Strong Buy" },
  Buy: { es: "Compra", en: "Buy" },
  Accumulate: { es: "Acumular", en: "Accumulate" },
  Watch: { es: "Vigilar", en: "Watch" },
  Hold: { es: "Mantener", en: "Hold" },
  Avoid: { es: "Evitar", en: "Avoid" },
  StrongAvoid: { es: "Evitar fuerte", en: "Strong Avoid" },
  StrongAccumulate: { es: "Acumular fuerte", en: "Strong Accumulate" },
  HoldWait: { es: "Mantener/Esperar", en: "Hold / Wait" },
  Neutral: { es: "Neutral", en: "Neutral" },
  Caution: { es: "Precaución", en: "Caution" },
  Distribute: { es: "Distribuir", en: "Distribute" },
};

const T = {
  es: {
    subjectDigest: "Resumen de inversiones",
    subjectAlert: "Alerta de cambio de valoración",
    headerSub: "Tu informe diario de mercado",
    quick: "Resumen",
    nChanges: "cambios de expectativa",
    nOpps: "oportunidades",
    nRisks: "alertas de riesgo",
    secChanges: "Cambios de expectativa en tu portfolio",
    secOpps: "Oportunidades de inversión",
    secRisks: "Alertas de riesgo",
    colSymbol: "Símbolo",
    colChange: "Cambio",
    colScore: "Score",
    colPrice: "Precio",
    colDay: "Día",
    colSignal: "Señal",
    colSector: "Sector",
    colUpside: "Potencial",
    noChanges: "Sin cambios de valoración desde el último informe.",
    noOpps: "No hay nuevas oportunidades destacadas en este momento.",
    earningsIn: "resultados en",
    days: "días",
    footer: "Generado automáticamente por Vantage. Esto no es asesoramiento financiero — verificá antes de operar.",
    movedTo: "→",
  },
  en: {
    subjectDigest: "Investment digest",
    subjectAlert: "Rating-change alert",
    headerSub: "Your daily market briefing",
    quick: "Summary",
    nChanges: "expectation changes",
    nOpps: "opportunities",
    nRisks: "risk alerts",
    secChanges: "Expectation changes in your portfolio",
    secOpps: "Investment opportunities",
    secRisks: "Risk alerts",
    colSymbol: "Symbol",
    colChange: "Change",
    colScore: "Score",
    colPrice: "Price",
    colDay: "Day",
    colSignal: "Signal",
    colSector: "Sector",
    colUpside: "Upside",
    noChanges: "No rating changes since the last briefing.",
    noOpps: "No standout new opportunities right now.",
    earningsIn: "earnings in",
    days: "days",
    footer: "Auto-generated by Vantage. This is not financial advice — verify before trading.",
    movedTo: "→",
  },
};

// ── formatters ──
const money = (cents: number) =>
  `$${(cents / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const labelName = (l: SetupLabel, lang: Lang) => LABELS[l]?.[lang] ?? l;
const labelColor = (l: SetupLabel) => (POS.includes(l) ? C.green : NEG.includes(l) ? C.red : C.gray);
const scoreStr = (s: number) => (s > 0 ? `+${s}` : `${s}`);
const dayCell = (bps: number | null) => {
  if (bps == null) return `<span style="color:${C.sub}">—</span>`;
  const v = bps / 100;
  const col = v > 0 ? C.green : v < 0 ? C.red : C.sub;
  const arrow = v > 0 ? "▲" : v < 0 ? "▼" : "";
  return `<span style="color:${col};font-weight:600">${arrow} ${v >= 0 ? "+" : ""}${v.toFixed(2)}%</span>`;
};

function badge(text: string, color: string): string {
  return `<span style="display:inline-block;padding:2px 8px;border-radius:10px;background:${color};color:#fff;font-size:12px;font-weight:700;white-space:nowrap">${text}</span>`;
}

function sectionHeader(text: string): string {
  return `<tr><td style="padding:24px 24px 10px">
    <table role="presentation" cellpadding="0" cellspacing="0"><tr>
      <td style="width:4px;background:${C.accent};border-radius:2px">&nbsp;</td>
      <td style="padding-left:10px;font-size:13px;font-weight:800;letter-spacing:.05em;text-transform:uppercase;color:${C.ink}">${text}</td>
    </tr></table></td></tr>`;
}

function shell(title: string, subtitle: string, inner: string, lang: Lang): string {
  const tx = T[lang];
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:${C.bg};font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${C.bg};padding:28px 12px">
<tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:${C.card};border-radius:16px;overflow:hidden;box-shadow:0 10px 34px rgba(0,0,0,.4)">
  <tr><td style="background:${C.ink};padding:26px 26px 22px">
    <div style="color:#fff;font-size:23px;font-weight:800;letter-spacing:-.02em">📈 Vantage</div>
    <div style="color:#cbd5e1;font-size:15px;font-weight:600;margin-top:8px">${title}</div>
    <div style="color:#64748b;font-size:12px;margin-top:2px">${subtitle}</div>
  </td></tr>
  <tr>
    <td style="height:4px;background:${C.green};font-size:0;line-height:0;mso-line-height-rule:exactly">&nbsp;</td>
  </tr>
  ${inner}
  <tr><td style="padding:20px 26px;border-top:1px solid ${C.line};background:${C.zebra};color:${C.sub};font-size:11px;line-height:1.6">${tx.footer}</td></tr>
</table>
</td></tr></table></body></html>`;
}

function dataTable(headers: string[], rows: string[], aligns: string[]): string {
  const ths = headers.map((h, i) =>
    `<th style="text-align:${aligns[i]};padding:9px 11px;font-size:10px;text-transform:uppercase;letter-spacing:.04em;color:${C.sub};background:${C.zebra};border-bottom:1px solid ${C.line}">${h}</th>`
  ).join("");
  return `<tr><td style="padding:2px 18px 6px">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:1px solid ${C.line};border-radius:8px">
      <thead><tr>${ths}</tr></thead><tbody>${rows.join("")}</tbody>
    </table></td></tr>`;
}

function td(content: string, align = "left", bold = false): string {
  return `<td style="padding:11px 11px;font-size:14px;color:${C.ink};text-align:${align};border-bottom:1px solid ${C.line};${bold ? "font-weight:700" : ""}">${content}</td>`;
}

// ── sections ──
function changesSection(changes: EmailChange[], lang: Lang): string {
  const tx = T[lang];
  if (changes.length === 0)
    return sectionHeader(tx.secChanges) + `<tr><td style="padding:4px 24px 8px;color:${C.sub};font-size:13px">${tx.noChanges}</td></tr>`;
  const rows = changes.map((c, i) => {
    const bg = i % 2 ? C.zebra : "#fff";
    const change = `${badge(labelName(c.from, lang), labelColor(c.from))} <span style="color:${C.sub}">${tx.movedTo}</span> ${badge(labelName(c.to, lang), labelColor(c.to))}`;
    const name = c.company ? `<div style="font-size:11px;color:${C.sub}">${esc(c.company)}</div>` : "";
    return `<tr style="background:${bg}">
      ${td(`<strong>${c.symbol}</strong>${name}`)}
      ${td(change)}
      ${td(scoreStr(c.score), "right", true)}
      ${td(money(c.priceCents), "right")}
      ${td(dayCell(c.dailyChangeBps), "right")}
    </tr>`;
  });
  return sectionHeader(tx.secChanges) +
    dataTable([tx.colSymbol, tx.colChange, tx.colScore, tx.colPrice, tx.colDay], rows, ["left", "left", "right", "right", "right"]);
}

function oppsSection(opps: EmailOpportunity[], lang: Lang): string {
  const tx = T[lang];
  if (opps.length === 0)
    return sectionHeader(tx.secOpps) + `<tr><td style="padding:4px 24px 8px;color:${C.sub};font-size:13px">${tx.noOpps}</td></tr>`;
  const rows = opps.map((o, i) => {
    const bg = i % 2 ? C.zebra : "#fff";
    const name = o.company ? `<div style="font-size:11px;color:${C.sub}">${esc(o.company)}</div>` : "";
    const earn = o.earningsEpoch != null
      ? (() => {
          const d = Math.floor((o.earningsEpoch * 1000 - Date.now()) / 86_400_000);
          return d >= 0 && d <= 14 ? ` <span style="color:${C.amber};font-size:11px">📅 ${tx.earningsIn} ${d}${lang === "es" ? "d" : "d"}</span>` : "";
        })()
      : "";
    const upside = o.upsidePct != null
      ? `<span style="color:${o.upsidePct >= 0 ? C.green : C.red};font-weight:600">${o.upsidePct >= 0 ? "+" : ""}${o.upsidePct.toFixed(0)}%</span>`
      : `<span style="color:${C.sub}">—</span>`;
    return `<tr style="background:${bg}">
      ${td(`<strong>${o.symbol}</strong>${name}`)}
      ${td(`${badge(labelName(o.label, lang), labelColor(o.label))}${earn}`)}
      ${td(scoreStr(o.score), "right", true)}
      ${td(money(o.priceCents), "right")}
      ${td(o.sector ? esc(o.sector) : "—")}
      ${td(upside, "right")}
    </tr>`;
  });
  return sectionHeader(tx.secOpps) +
    dataTable([tx.colSymbol, tx.colSignal, tx.colScore, tx.colPrice, tx.colSector, tx.colUpside], rows, ["left", "left", "right", "right", "left", "right"]);
}

function risksSection(risks: EmailRiskAlert[], lang: Lang): string {
  const tx = T[lang];
  if (risks.length === 0) return "";
  const items = risks.map((r) => {
    const col = r.severity === "danger" ? C.red : C.amber;
    return `<tr><td style="padding:6px 24px;font-size:13px;color:${C.ink}">
      <span style="color:${col};font-weight:700">●</span> <strong>${r.symbol}</strong> — ${esc(r.text)}
    </td></tr>`;
  }).join("");
  return sectionHeader(tx.secRisks) + items;
}

function quickSummary(d: DigestData): string {
  const tx = T[d.lang];
  const chip = (n: number, label: string, color: string) =>
    `<td width="33%" style="padding:0 6px" valign="top">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${C.zebra};border:1px solid ${C.line};border-radius:12px">
        <tr><td style="padding:14px 10px;text-align:center">
          <div style="font-size:30px;font-weight:800;line-height:1;color:${color}">${n}</div>
          <div style="font-size:11px;color:${C.sub};margin-top:6px;text-transform:uppercase;letter-spacing:.03em">${label}</div>
        </td></tr>
      </table></td>`;
  return `<tr><td style="padding:20px 18px 4px">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr>
      ${chip(d.changes.length, tx.nChanges, C.accent)}
      ${chip(d.opportunities.length, tx.nOpps, C.green)}
      ${chip(d.risks.length, tx.nRisks, C.amber)}
    </tr></table></td></tr>`;
}

// ── public builders ──
export function buildDigestEmail(d: DigestData): { subject: string; html: string; text: string } {
  const tx = T[d.lang];
  const dateStr = d.now.toLocaleDateString(d.lang === "es" ? "es-AR" : "en-US",
    { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  const inner =
    quickSummary(d) +
    changesSection(d.changes, d.lang) +
    oppsSection(d.opportunities, d.lang) +
    risksSection(d.risks, d.lang);
  const subject = `${SUBJECT_PREFIX} 📈 ${tx.subjectDigest} — ${d.changes.length} ${tx.nChanges}, ${d.opportunities.length} ${tx.nOpps}`;
  const subtitle = `${cap(dateStr)} · ${tx.headerSub}`;
  return { subject, html: shell(tx.subjectDigest, subtitle, inner, d.lang), text: digestText(d) };
}

export function buildAlertEmail(changes: EmailChange[], lang: Lang): { subject: string; html: string; text: string } {
  const tx = T[lang];
  const inner = changesSection(changes, lang);
  const lead = changes[0];
  const subject = changes.length === 1
    ? `${SUBJECT_PREFIX} ⚠️ ${lead.symbol}: ${labelName(lead.from, lang)} ${tx.movedTo} ${labelName(lead.to, lang)}`
    : `${SUBJECT_PREFIX} ⚠️ ${tx.subjectAlert} — ${changes.length} ${tx.nChanges}`;
  const subtitle = new Date().toLocaleString(lang === "es" ? "es-AR" : "en-US");
  return { subject, html: shell(tx.subjectAlert, subtitle, inner, lang), text: changesText(changes, lang) };
}

// ── plain-text fallbacks ──
function digestText(d: DigestData): string {
  const tx = T[d.lang];
  const lines: string[] = [`Vantage — ${tx.subjectDigest}`, ""];
  lines.push(`${tx.secChanges}:`);
  if (d.changes.length === 0) lines.push(`  ${tx.noChanges}`);
  else d.changes.forEach((c) => lines.push(`  ${c.symbol}: ${labelName(c.from, d.lang)} -> ${labelName(c.to, d.lang)} (score ${scoreStr(c.score)}, ${money(c.priceCents)})`));
  lines.push("", `${tx.secOpps}:`);
  if (d.opportunities.length === 0) lines.push(`  ${tx.noOpps}`);
  else d.opportunities.forEach((o) => lines.push(`  ${o.symbol}: ${labelName(o.label, d.lang)} (score ${scoreStr(o.score)}, ${money(o.priceCents)})`));
  if (d.risks.length) { lines.push("", `${tx.secRisks}:`); d.risks.forEach((r) => lines.push(`  ${r.symbol}: ${r.text}`)); }
  lines.push("", tx.footer);
  return lines.join("\n");
}
function changesText(changes: EmailChange[], lang: Lang): string {
  return changes.map((c) => `${c.symbol}: ${labelName(c.from, lang)} -> ${labelName(c.to, lang)} (${money(c.priceCents)})`).join("\n");
}

// ── utils ──
function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
