mod market_data;
mod persistence;
mod profiles;
mod tui;
mod tui_graphs;

use std::backtrace::Backtrace;
use std::cmp::Ordering;
use std::collections::HashMap;
use std::collections::HashSet;
use std::collections::VecDeque;
use std::error::Error;
use std::fmt;
use std::io;
use std::io::ErrorKind;
use std::io::Stdout;
use std::io::Write;
use std::panic;
use std::panic::AssertUnwindSafe;
use std::panic::PanicHookInfo;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::Mutex;
use std::sync::OnceLock;
use std::sync::mpsc;
use std::thread;
use std::time::Duration;
use std::time::Instant;
use std::time::SystemTime;
use std::time::UNIX_EPOCH;

use crossterm::cursor::Hide;
use crossterm::cursor::Show;
use crossterm::event;
use crossterm::event::Event;
use crossterm::event::KeyCode;
use crossterm::event::KeyEvent;
use crossterm::event::KeyEventKind;
use crossterm::event::KeyModifiers;
use crossterm::execute;
use crossterm::style::Color;
use crossterm::terminal;
use crossterm::terminal::EnterAlternateScreen;
use crossterm::terminal::LeaveAlternateScreen;
use discount_screener::AlertEvent;
use discount_screener::AlertKind;
use discount_screener::CandidateRow;
use discount_screener::ConfidenceBand;
use discount_screener::ExternalSignalStatus;
use discount_screener::ExternalValuationSignal;
use discount_screener::FundamentalSnapshot;
use discount_screener::MarketSnapshot;
use discount_screener::QualificationStatus;
use discount_screener::SymbolDetail;
use discount_screener::TapeEvent;
use discount_screener::TerminalState;
use discount_screener::ViewFilter;
use discount_screener::checked_gap_bps;
use market_data::ChartRange;
use market_data::DEFAULT_POLL_INTERVAL;
use market_data::FundamentalTimeseries;
use market_data::HistoricalCandle;
use market_data::MarketDataClient;
use market_data::default_live_symbols;
use persistence::PersistedChartRecord;
use persistence::PersistedIssueRecord;
use persistence::PersistenceBootstrap;
use persistence::PersistenceHandle;
use persistence::PersistenceStatusEvent;
use profiles::profile_definitions;
use profiles::profile_symbols;
use ratatui::Terminal;
use ratatui::backend::CrosstermBackend;
use serde::Deserialize;
use serde::Serialize;

const MAX_VISIBLE_ALERTS: usize = 6;
const MAX_VISIBLE_TAPE: usize = 8;
const MAX_VISIBLE_ISSUES: usize = 8;
const MAX_STORED_ISSUES: usize = 64;
const MAX_VISIBLE_ROWS: usize = 20;
const WEIGHTED_TARGET_REFRESH_BUDGET_PER_CYCLE: usize = 8;
const CANDIDATE_COMPANY_COLUMN_WIDTH: usize = 36;
const TARGET_RANGE_BAR_WIDTH: usize = 18;
const GAP_METER_WIDTH: usize = 12;
const DETAIL_CONSENSUS_BAR_WIDTH: usize = 20;
const DETAIL_RECENT_SUMMARY_COUNT: usize = 4;
#[cfg(test)]
const DEFAULT_VIEWPORT_WIDTH: usize = 120;
#[cfg(test)]
const DEFAULT_VIEWPORT_HEIGHT: usize = 40;
const DETAIL_MIN_CHART_HEIGHT: usize = 6;
const DETAIL_MIN_VISIBLE_CANDLES: usize = 8;
const DETAIL_MIN_VOLUME_HEIGHT: usize = 3;
const DETAIL_MIN_MACD_HEIGHT: usize = 4;
const DETAIL_CHART_AXIS_WIDTH: usize = 12;
const DETAIL_CHART_ROW_PADDING: usize = 2;
const DETAIL_VOLUME_PROFILE_WIDTH: usize = 20;
const BACKGROUND_CHART_REQUEST_BUDGET_PER_CYCLE: usize = 6;
const INLINE_STYLE_MARKER: char = '\u{001f}';
const DEFAULT_FEED_ERROR_LOG_FILE: &str = "feed-errors.log";
const DEFAULT_CRASH_REPORT_LOG_FILE: &str = "crash-report.log";
const ISSUE_TOAST_DURATION: Duration = Duration::from_secs(6);
const EVENT_RATE_WINDOW: Duration = Duration::from_secs(1);
const ISSUE_KEY_FEED_UNAVAILABLE: &str = "feed-unavailable";
const ISSUE_KEY_FEED_PARTIAL: &str = "feed-partial";
const ISSUE_KEY_SQLITE_PERSISTENCE: &str = "sqlite-persistence";
const ISSUE_KEY_SQLITE_RESTORE: &str = "sqlite-restore";
const ISSUE_KEY_HISTORY_EXPORT: &str = "history-export";
#[cfg(test)]
const ISSUE_KEY_JOURNAL_RESTORE: &str = ISSUE_KEY_SQLITE_RESTORE;
#[cfg(test)]
const ISSUE_KEY_WATCHLIST_RESTORE: &str = ISSUE_KEY_SQLITE_RESTORE;
const RISK_FREE_RATE_BPS: i32 = 400;
const EQUITY_RISK_PREMIUM_BPS: i32 = 500;
const DEFAULT_TAX_RATE_BPS: i32 = 2_100;
const DEFAULT_COST_OF_DEBT_BPS: i32 = 550;
const MIN_COST_OF_DEBT_BPS: i32 = 200;
const MAX_COST_OF_DEBT_BPS: i32 = 1_200;
const MIN_WACC_BPS: i32 = 500;
const MAX_WACC_BPS: i32 = 1_800;
const DCF_PROJECTION_YEARS: usize = 5;
const BASE_GROWTH_MIN_BPS: i32 = -1_000;
const BASE_GROWTH_MAX_BPS: i32 = 1_800;
const SCENARIO_GROWTH_SPREAD_BPS: i32 = 400;
const BEAR_GROWTH_MIN_BPS: i32 = -1_200;
const BEAR_GROWTH_MAX_BPS: i32 = 1_400;
const BULL_GROWTH_MIN_BPS: i32 = -400;
const BULL_GROWTH_MAX_BPS: i32 = 2_400;
const BEAR_TERMINAL_GROWTH_BPS: i32 = 200;
const BASE_TERMINAL_GROWTH_BPS: i32 = 250;
const BULL_TERMINAL_GROWTH_BPS: i32 = 300;
const DCF_OPPORTUNITY_THRESHOLD_BPS: i32 = 2_000;
const DCF_EXPENSIVE_THRESHOLD_BPS: i32 = -1_000;
const MIN_RELATIVE_PEERS: usize = 5;
const STRONG_RELATIVE_SCORE: u8 = 67;
const WEAK_RELATIVE_SCORE: u8 = 34;
const MIN_FEED_FETCH_CONCURRENCY: usize = 1;
const START_FEED_FETCH_CONCURRENCY: usize = 2;
const MAX_FEED_FETCH_CONCURRENCY: usize = 4;
const INITIAL_FEED_REFRESH_BUDGET: usize = 32;

include!("workstation/app_core.rs");
include!("workstation/runtime.rs");
include!("workstation/rendering.rs");
include!("workstation/startup.rs");
#[cfg(test)]
include!("workstation/tests.rs");
